### ISSUE TITLE
Is this package ready for registeration?

### ISSUE THREAD

**Issue by hz-xiaxz** [aryavorskiy/LatticeModels.jl#6]
Hello, thank you for publishing this good package! But I found this package not registered in Julia's general registry. Is it only in an early age of development or you have just forgot to register?

**Comment by aryavorskiy** [comment]
Hello! 

This package is ready for registration and even [almost registered](https://github.com/JuliaRegistries/General/pull/115363) – I just didn't know there is a three-day waiting time. By Saturday everything should be OK. Until that you can install it using the direct link:

```julia
import Pkg; Pkg.add(url="https://github.com/aryavorskiy/LatticeModels.jl")
```

**Comment by hz-xiaxz** [comment]
Good, thank you!
